// Code generated by mockery. DO NOT EDIT.

package mock_syncinterfaces

import (
	context "context"

	pgx "github.com/jackc/pgx/v4"
	mock "github.com/stretchr/testify/mock"

	state "github.com/0xPolygonHermez/zkevm-node/state"
)

// StateBlobSequenceWriter is an autogenerated mock type for the StateBlobSequenceWriter type
type StateBlobSequenceWriter struct {
	mock.Mock
}

type StateBlobSequenceWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *StateBlobSequenceWriter) EXPECT() *StateBlobSequenceWriter_Expecter {
	return &StateBlobSequenceWriter_Expecter{mock: &_m.Mock}
}

// AddBlobSequence provides a mock function with given fields: ctx, blobSequence, dbTx
func (_m *StateBlobSequenceWriter) AddBlobSequence(ctx context.Context, blobSequence *state.BlobSequence, dbTx pgx.Tx) error {
	ret := _m.Called(ctx, blobSequence, dbTx)

	if len(ret) == 0 {
		panic("no return value specified for AddBlobSequence")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *state.BlobSequence, pgx.Tx) error); ok {
		r0 = rf(ctx, blobSequence, dbTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StateBlobSequenceWriter_AddBlobSequence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBlobSequence'
type StateBlobSequenceWriter_AddBlobSequence_Call struct {
	*mock.Call
}

// AddBlobSequence is a helper method to define mock.On call
//   - ctx context.Context
//   - blobSequence *state.BlobSequence
//   - dbTx pgx.Tx
func (_e *StateBlobSequenceWriter_Expecter) AddBlobSequence(ctx interface{}, blobSequence interface{}, dbTx interface{}) *StateBlobSequenceWriter_AddBlobSequence_Call {
	return &StateBlobSequenceWriter_AddBlobSequence_Call{Call: _e.mock.On("AddBlobSequence", ctx, blobSequence, dbTx)}
}

func (_c *StateBlobSequenceWriter_AddBlobSequence_Call) Run(run func(ctx context.Context, blobSequence *state.BlobSequence, dbTx pgx.Tx)) *StateBlobSequenceWriter_AddBlobSequence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*state.BlobSequence), args[2].(pgx.Tx))
	})
	return _c
}

func (_c *StateBlobSequenceWriter_AddBlobSequence_Call) Return(_a0 error) *StateBlobSequenceWriter_AddBlobSequence_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateBlobSequenceWriter_AddBlobSequence_Call) RunAndReturn(run func(context.Context, *state.BlobSequence, pgx.Tx) error) *StateBlobSequenceWriter_AddBlobSequence_Call {
	_c.Call.Return(run)
	return _c
}

// NewStateBlobSequenceWriter creates a new instance of StateBlobSequenceWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateBlobSequenceWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateBlobSequenceWriter {
	mock := &StateBlobSequenceWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
